# Generated by Django 4.2 on 2023-04-17 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_iamge',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_video',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
