# Generated by Django 4.2 on 2023-04-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_courses_user_courses_course_iamge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
